name: Security Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for SonarCloud
      - name: SonarCloud Scan
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    
        with:
          args: >
            -Dsonar.projectKey=Chamisew_Cloud-Microservices-Assignment-2026
            -Dsonar.organization=chamisew
